### ISSUE TITLE
valueString voorbeelden met zonder /

### ISSUE THREAD

**Issue by willemsendennis** [jorritspee/nuts-use-case-profile-bgz-referral#2]
De references in de korte voorbeelden onder [Workflow Task Input Elements](https://github.com/nuts-foundation/nuts-use-case-profile-bgz-referral?tab=readme-ov-file#workflow-task-input-elements) starten met een / in de valueString. Dit is niet conform FHIR Literal References (en ook niet conform het uitgebreide voorbeeld eronder).

**Comment by jorritspee** [comment]
Dank, dit zal ik gelijk even aanpassen.

**Comment by jorritspee** [comment]
Done. Nieuwe versie is 1.1.0 ;-)

**Comment by willemsendennis** [comment]
Thanks!
